### PR TITLE
Feature/client entity

### PR DESCRIPTION
**Pull request by carlosgm128**
added client schema and interfaces, and also added respective dependencies

### CODE REVIEW

**Review by Eduard177 — DISMISSED** [review]

**Review by Jhomiguel — COMMENTED** [review]
The file should be camel case: 
instead of Client.entity.ts, should be client.entity.ts

**Review by Jhomiguel — COMMENTED** [review]
instead of updateAt, createAd... 
use createdAt and uddatedAt

**Comment by Eduard177** [comment]
> instead of updateAt, createAd... use createdAt and uddatedAt

@Jhomiguel updatedAt

**Comment by carlosgm128** [comment]
@Jhomiguel  the changes are done

**Review by devRauLuis — APPROVED** [review]
This looks good now, approved

**Review by Eduard177 — APPROVED** [review]

**Pull request merged**
